version: '3.8'

services:
  mysql-dev:
    container_name: ${MYSQL_CONTAINER_NAME:-oa-mysql-dev}
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-oa_system_dev}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - oa_network_dev

  backend-dev:
    container_name: ${BACKEND_CONTAINER_NAME:-oa-backend-dev}
    build:
      context: ../../server
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - INIT_DB=false
    env_file:
      - ../../server/.env.development
    volumes:
      - ../../server/uploads:/app/uploads
    depends_on:
      - mysql-dev
    networks:
      - oa_network_dev

  frontend-dev:
    container_name: ${FRONTEND_CONTAINER_NAME:-oa-frontend-dev}
    build:
      context: ../../web
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - ../../web/.env.development
    volumes:
      - ../../web:/app
      - /app/node_modules
    networks:
      - oa_network_dev

networks:
  oa_network_dev:
    driver: bridge

volumes:
  mysql_data_dev: 