services:
  mysql-dev:
    container_name: ${MYSQL_CONTAINER_NAME:-oa-mysql-dev}
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-oa_system_dev}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      TZ: Asia/Taipei
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-time-zone=+08:00']
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - oa_network_dev

  backend-dev:
    container_name: ${BACKEND_CONTAINER_NAME:-oa-backend-dev}
    build:
      context: ../../server
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - INIT_DB=false
      - NODE_ENV=development
      - NODE_OPTIONS="--max-old-space-size=2048"
    env_file:
      - ../../server/.env.development
    volumes:
      - ../../server:/app:cached
      - backend_node_modules:/app/node_modules
      - ../../server/uploads:/app/uploads
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
        reservations:
          memory: 512M
    depends_on:
      - mysql-dev
    networks:
      - oa_network_dev

  frontend-dev:
    container_name: ${FRONTEND_CONTAINER_NAME:-oa-frontend-dev}
    build:
      context: ../../web
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS="--max-old-space-size=2048"
    env_file:
      - ../../web/.env.development
    volumes:
      - ../../web:/app:cached
      - frontend_node_modules:/app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
        reservations:
          memory: 512M
    networks:
      - oa_network_dev

networks:
  oa_network_dev:
    driver: bridge

volumes:
  mysql_data_dev:
  frontend_node_modules:
  backend_node_modules: 