version: '3.8'

services:
  mysql-prod:
    container_name: ${MYSQL_CONTAINER_NAME:-oa-mysql-prod}
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-oa_system_prod}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
    networks:
      - oa_network_prod
    restart: always

  backend-prod:
    container_name: ${BACKEND_CONTAINER_NAME:-oa-backend-prod}
    build:
      context: ../../server
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - ../../server/.env.production
    depends_on:
      - mysql-prod
    networks:
      - oa_network_prod
    restart: always

  frontend-prod:
    container_name: ${FRONTEND_CONTAINER_NAME:-oa-frontend-prod}
    build:
      context: ../../web
      dockerfile: Dockerfile.prod
    ports:
      - "${FRONTEND_PORT:-80}:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - ../../web/.env.production
    networks:
      - oa_network_prod
    restart: always

networks:
  oa_network_prod:
    driver: bridge

volumes:
  mysql_data_prod: 