version: '3.8'

services:
  mysql-prod:
    container_name: ${MYSQL_CONTAINER_NAME:-oa-mysql-prod}
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-oa_system_prod}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Taipei
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-time-zone=+08:00']
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - oa_network_prod
    restart: always

  backend-prod:
    container_name: ${BACKEND_CONTAINER_NAME:-oa-backend-prod}
    build:
      context: ../../server
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ../../server/uploads:/app/uploads
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../../server/.env.production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
        reservations:
          memory: 1G
    depends_on:
      - mysql-prod
    networks:
      - oa_network_prod
    restart: always

  frontend-prod:
    container_name: ${FRONTEND_CONTAINER_NAME:-oa-frontend-prod}
    build:
      context: ../../web
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    ports:
      - "${FRONTEND_PORT:-80}:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ../../server/uploads:/usr/share/nginx/html/uploads:ro
      - ../../web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../../web/.env.production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - oa_network_prod
    restart: always

networks:
  oa_network_prod:
    driver: bridge

volumes:
  mysql_data_prod:
  uploads_data:
    driver: local
    driver_opts:
      type: none
      device: /var/www/uploads
      o: bind 