# 依賴階段
FROM node:18-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production \
    && npm cache clean --force

# 開發階段
FROM node:18-alpine
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY package*.json ./
RUN npm install --only=development

# 設置環境變量和權限
ENV NODE_ENV=development
ENV PATH /app/node_modules/.bin:$PATH

RUN mkdir -p uploads \
    && chown -R node:node /app

USER node
EXPOSE 3001

CMD ["npm", "run", "dev"] 